export const LOAD_FORTS_SUCCESS = 'LOAD_FORTS_SUCCESS';
export const CREATE_FORT_SUCCESS = 'CREATE_FORT_SUCCESS';
export const UPDATE_FORT_SUCCESS = 'UPDATE_FORT_SUCCESS';
export const DELETE_FORT_SUCCESS = 'DELETE_FORT_SUCCESS';
export const CREATE_CUSTOMERINFO_SUCCESS = 'CREATE_CUSTOMERINFO_SUCCESS';
export const CHECK_CUSTOMERINFO_SUCCESS = 'CHECK_CUSTOMERINFO_SUCCESS';

